### PR TITLE
Applicative CE for PromiseBuilder

### PR DESCRIPTION
**Pull request by delneg**
I've started some work on `and!` support, but I'm don't know if we should or should not use BindReturn, as currently (if you uncomment it) it has a different signature than `andFor`

With `BindReturn`:

```js
it("Promise can be run in parallel with andFor extension", () => {
        const one = Promise.resolve(1);
        const two = Promise.resolve(2);
        return tap((result_5) => {
            assertEqual(3, result_5);
        }, PromiseBuilder__Run_212F1D4B(promise, PromiseBuilder__Delay_62FBFDE1(promise, () => ((Promise.all([one,two]).then(([a,b]) => ((a_15, b_1) => [a_15, b_1])(a,b))).then(((_arg35) => (Promise.resolve((_arg35[0] + _arg35[1])))))))));
    });
    it("Promise can be run in parallel with and!", () => {
        const one_1 = Promise.resolve(1);
        const two_1 = Promise.resolve(2);
        return tap((result_6) => {
            assertEqual(3, result_6);
        }, PromiseBuilder__Run_212F1D4B(promise, PromiseBuilder__Delay_62FBFDE1(promise, () => PromiseBuilder__BindReturn_3B59CB7D(promise, Promise.all([one_1,two_1]), (_arg36) => (_arg36[0] + _arg36[1])))));
    });
```

Without `BindReturn`:
```js
it("Promise can be run in parallel with andFor extension", () => {
        const one = Promise.resolve(1);
        const two = Promise.resolve(2);
        return tap((result_5) => {
            assertEqual(3, result_5);
        }, PromiseBuilder__Run_212F1D4B(promise, PromiseBuilder__Delay_62FBFDE1(promise, () => ((Promise.all([one,two]).then(([a,b]) => ((a_15, b_1) => [a_15, b_1])(a,b))).then(((_arg35) => (Promise.resolve((_arg35[0] + _arg35[1])))))))));
    });
    it("Promise can be run in parallel with and!", () => {
        const one_1 = Promise.resolve(1);
        const two_1 = Promise.resolve(2);
        return tap((result_6) => {
            assertEqual(3, result_6);
        }, PromiseBuilder__Run_212F1D4B(promise, PromiseBuilder__Delay_62FBFDE1(promise, () => ((Promise.all([one_1,two_1])).then(((_arg36) => (Promise.resolve((_arg36[0] + _arg36[1])))))))));
    });
```

### CODE REVIEW

**Comment by delneg** [comment]
Summoning @alfonsogarciacaro for steps to go further (or merge as-is, the tests pass and i suppose it works, dunno)

**Comment by alfonsogarciacaro** [comment]
TBH, I haven't checked yet how `and!` desugars the code 😅 Thanks a lot for the PR, I will download it and give it a go to try to reply your question.

**Comment by delneg** [comment]
More information is also available in the RFC:
https://github.com/fsharp/fslang-design/blob/master/FSharp-5.0/FS-1063-support-letbang-andbang-for-applicative-functors.md

**Comment by alfonsogarciacaro** [comment]
Hi @delneg! Sorry, forgot about the review 😅 I've been reading the RFC and if my understanding is correct `BindReturn` is an opportunity to remove some calculations but I don't think we need it for JS Promise. Although it can be beneficial to implement some extra `MergeSources` like `MergeSources3`, `MergeSources4`...

```fsharp
    [<Emit("Promise.all([$1, $2, $3])")>]
    member x.MergeSources3(a: JS.Promise<'T1>, b: JS.Promise<'T2>, c: JS.Promise<'T3>): JS.Promise<'T1 * 'T2 * 'T3>= jsNative

    [<Emit("Promise.all([$1, $2, $3, $4])")>]
    member x.MergeSources4(a: JS.Promise<'T1>, b: JS.Promise<'T2>, c: JS.Promise<'T3>, d: JS.Promise<'T4>): JS.Promise<'T1 * 'T2 * 'T3 * 'T4>= jsNative
```

**Comment by alfonsogarciacaro** [comment]
Also, in the tests I would include some delays and side effects to make sure the promises are being run in parallel. For example:

```fsharp
    it "Promise can run multiple tasks in parallel with and!" <| fun () ->
        let mutable s = ""
        let doWork ms letter = {
            Promise.sleep ms
            s <- s + letter
            return letter
        }
        let one = doWork 1000 "a"
        let two = doWork 500 "b"
        let three = doWork 200 "c"
        promise {
            let! a = one
            and! b = two
            and! c = three
            return a + b + c
        }
        |> Promise.tap (fun result ->
            result |> equal "abc"
            s |> equal "cba"
        )
```

**Comment by delneg** [comment]
Done & done

**Comment by alfonsogarciacaro** [comment]
Thanks a lot @delneg! I will publish a new release :+1:

**Pull request merged**
