### PR TITLE
allow user-defined Source overloads for interop with user-defined types

### PR DESCRIPTION
**Pull request by baronfel**
Right now it's hard to interoperate with Thenables that are defined by ts2fable without writing a ton of mapping functions like `Thenable.ofPromise`, `Thenable.toPromise`, and matching module members on `Promise`.

This PR uses the `Source` mechanism in CEs to make this a user-solveable problem.  As soon as some basic `Source` overloads are defined (for the reflexive-self-type and for the seq overload), users can define their own `.Source` overloads that teach the CE how to convert from their types to Promise.

For example, in Ionide's VSCode typings we could add an overload for the Thenable type defined in those types like so:

```fsharp
type PromiseBuilder with
	member x.Source(t: Thenable<'t>): JS.Promise<'t> = t // this works because thenables _are_ isometric for most purposes
```

There are a few caveats with this refactoring, though:
* it's no longer possible to `return! failwith "blah"`, because the exact type returned by `failwith` is not pinned, and so no `Source` overload can be chosen
* for some reason, there's an interaction between SRTP operator overloading and Source overloading, such that the tests that used the unbox operator to coerce a `Promise<'t>` into a `U2<'t, Promise<'t>>` no longer compiled. I _think_ this is because the SRTP coercion didn't have a definite destination type to 'fix' either side of the U2, so either one of the cases could have been the staticaly-known `Promise<'t>`. Personally, this is an acceptable tradeoff to me in order to allow for user-defined types to integrate into the CE, but I wanted to bring this up to spark the discussion.

### CODE REVIEW

**Comment by MangelMaxime** [comment]
>     * it's no longer possible to `return! failwith "blah"`, because the exact type returned by `failwith` is not pinned, and so no `Source` overload can be chosen

Does `return failwith "blah!"` works? Because sometimes it is need to make F# compiler when wanting to throw from the promise for fast exit for example or just reach the fail path?

**Comment by baronfel** [comment]
@MangelMaxime yep, that works fine, and is what I've changed the tests here to do.  It begins failing because 'return!' ends up passing the right-hand side into the Source member, and as soon as there are two or more Source overloads, 'failwith'  cannot use the input type of Source to help pin its own type.

**Comment by MangelMaxime** [comment]
Ah yes sorry I didn't look at the code diff ^^ thank you for confirming.

**Comment by baronfel** [comment]
For what it's worth this is not a problem unique to the promise CE. I spent a good amount of time pair programming with @theangrybyd and he tried this same thing in FsToolkit.ErrorHandling and came to the same conclusion.

**Comment by inosik** [comment]
Can you add some kind of documentation for this? I didn't know this trick existed.

**Comment by baronfel** [comment]
@inosik of course!  Though some of this is just coming from the f# spec, I think a good example in the tests and the docs for this project (if anyone can point me to them?) would help.

**Comment by baronfel** [comment]
I added an example of a user-defined Thenable type to the tests to verify compatibility.

**Comment by MangelMaxime** [comment]
If possible before merging, please wait for https://github.com/baronfel/fable-promise/pull/1 to be merge into this PR.

**Comment by baronfel** [comment]
done!

**Comment by alfonsogarciacaro** [comment]
Thanks @baronfel! Actually, I never liked the signature of `either` that makes the code more complicated and it's not consistent with other functions. With the recent polishing it's probably a good opportunity to release a new major version and allow a small breaking change to "fix" either by doubling it into `either/eitherBind` and accepting only `exn` for the error case (as with `Promise.catch`).

**Comment by alfonsogarciacaro** [comment]
I've published 3.0.0-beta-001 with recent changes. Please give it a try if possible and let me know if something is broken :)

**Comment by baronfel** [comment]
working just fine in ionide-vscode-fsharp after the update, all I had to do was add my `Source` overload for Thenables :)

**Comment by alfonsogarciacaro** [comment]
I just realized that because of #14 just casting Thenables to Promises is not going to work when catching errors. Will you take care of that in Ionide's code @baronfel or should we at least update the sample provided by this PR? (Or maybe we should go back to only using `.then`?)

As a side node, I'm testing 3.0 beta in one project and when refactoring I'm getting this error quite often:

```
A unique overload for method 'Source' could not be determined based on type information prior to this program point. A type annotation may be needed.
```

It goes away when adding a type annotation as the message says, but it's strange because the problem is usually in another function and the Promise type is correctly inferred. I hope it's not confusing for users who don't know about `.Source` in CEs.

**Comment by alfonsogarciacaro** [comment]
Hmm, while refactoring my project using fable-promise 3.0 beta I'm seeing the error above more and more times. And sometimes the fix is not immediately obvious or it hides the actual error (see image below). I'm concerned because I don't know of other projects besides Ionide (which already deals with `promise` CE without `Source`) that would use this,  but on the other hand this can be an annoyance for most users. So I'm wondering if we should revert this PR?

image

Thoughts? @baronfel @MangelMaxime

**Comment by baronfel** [comment]
Which library is in use here? There might be a need for libraries that use a type that is JS-coercible to a promise/thenable to add those members.  The problem is kind of circular in that without the source overload defined, you can't reasonably expect libraries to provide a source overload themselves due to compilation errors that are introduced....

**Comment by alfonsogarciacaro** [comment]
Besides Fable.Promise no libraries are used in this particular example. The rest is custom code. We do have a `PromiseResult` type including a `promiseResult` CE, but we convert manually promises to promise results where needed. This may be creating some frictions (although we didn't have these issues before) but in the particular example of the screenshot above I'm just inside a `promise` CE and with methods returning promises. The problem here is I added an extra `.Where` so the expression is an error, the compiler cannot infer it's type and the Source overload cannot be resolved. I'm worried that in these situations users get confused because the overload resolution is not the real problem here, but it's what appears first and takes the most space in the tooltip.

**Comment by MangelMaxime** [comment]
Well, in general people should read error messages all the way to the bottom 😉

I think that if they see this error once and struggle with it, they will just remember that it is possible that it is possible that there is a second error reported after it.

I often, see multiple errors reported by F# compiler and need to read all of them to know which one is relevant here or not etc.

On my side, I did port a full project to the beta version without much problems beside the one I reported/fixed here #18

**Pull request merged**
